// The Overresponsible AI Handbook: a standalone Typst book.
// Consumes /book_map.yaml (generated by scripts/build_map.py) and the pandoc
// fragments in /pdf/_generated/ (generated by scripts/build_pdf.sh).
// Compile: typst compile --root book book/pdf/main.typ book/exports/overresponsible-ai-handbook.pdf
//
// Page architecture (deliberately mixed orientation):
//   portrait:  cover, front matter, letter-grid index, back matter, coloring section
//   landscape: the 26 letter pages ONLY (facer poster left, koan right)

#let map = yaml("/book_map.yaml")

// One accent color, sampled from the cover's laurel rust (#C26A3D), darkened
// for use as text on white.
#let accent = rgb("#9B5531")
#let serif = ("Baskerville", "Georgia", "Libertinus Serif")

#set document(
  title: map.meta.title + ": " + map.meta.subtitle,
  author: map.meta.author,
)
#set text(font: serif, size: 11.5pt)
#set par(justify: true, leading: 0.7em)
#set page(paper: "us-letter", margin: (x: 1.1in, y: 1in))

// Heading styles for the pandoc fragments (their H1s = book sections).
#show heading.where(level: 1): it => {
  v(0.6em)
  text(size: 20pt, weight: "bold", fill: accent, it.body)
  v(0.5em)
}
#show link: set text(fill: accent.darken(15%))

// Zero-size, invisible heading that still lands in the PDF outline.
#let bookmark(lvl, title) = {
  place(hide(heading(level: lvl, outlined: true, title)))
}
// Named jump target: query(metadata.where(value: name)).
#let anchor(name) = place(metadata(name))
#let jump(name, body) = context {
  let hits = query(metadata.where(value: name))
  if hits.len() > 0 { link(hits.first().location(), body) } else { body }
}

// ===== Cover: portrait, full-bleed =====
// The art is 2:3; US Letter is 0.773. fit "cover" would crop the title and
// tagline off the art, so: contain, on a page filled with the art's own edge
// color (sampled #E8C690): reads as full-bleed without losing a pixel.
#page(margin: 0pt, footer: none, fill: rgb("#E8C690"))[
  #align(center + horizon,
    image("/images/cover.jpg", width: 100%, height: 100%, fit: "contain"))
]

// ===== Front matter (pandoc fragments, TOC rendered natively between them) =====
#set page(numbering: "1", number-align: center)
#counter(page).update(1)

#include "/pdf/_generated/front_pre_toc.typ"

#pagebreak(weak: true)
#heading(level: 1, outlined: true)[Table of Contents]
#let find-id(ids, prefix) = ids.find(id => id.starts-with(prefix))
// Real TOC entry: leader dots + the actual page number, whole row linked.
#let toc-entry(name, title) = context {
  let hits = query(metadata.where(value: name))
  if hits.len() > 0 {
    let loc = hits.first().location()
    let pg = counter(page).at(loc).first()
    block(inset: (y: 0.45em), width: 100%,
      link(loc)[#title #box(width: 1fr, repeat(gap: 4pt)[.]) #pg])
  } else { block(title) }
}
#v(0.5em)
#toc-entry("sec-" + find-id(map.front, "foreword"), [Foreword])
#toc-entry("sec-" + find-id(map.front, "author_s_note"), [Author's Note])
#toc-entry("grid-index", [The Alphabet])
#toc-entry("sec-" + find-id(map.back, "afterword"), [Afterword])
#toc-entry("sec-" + find-id(map.back, "the_abbreviated_compendium"), [The Abbreviated Compendium])
#toc-entry("coloring-section", [Coloring Pages])

#pagebreak(weak: true)
#include "/pdf/_generated/front_post_toc.typ"

// ===== Letter-grid index: typographic, links to each letter page =====
#pagebreak()
#anchor("grid-index")
#heading(level: 1, outlined: true)[The Alphabet]
// Reusable letter grid: the coloring section opens with the same component.
#let letter-grid(prefix, cell: 1.15in, size: 46pt) = align(center)[
  #grid(
    columns: (cell,) * 5,
    rows: (cell,) * 6,
    ..map.letters.map(l => align(center + horizon, jump(
      prefix + l.letter,
      text(size: size, weight: "bold", fill: accent, l.letter),
    ))),
  )
]
#text(style: "italic", size: 10.5pt, fill: luma(30%))[
  Select any letter below to be transported directly to its designated instructional
  unit. All navigation pathways have been risk-assessed and approved for your safety.
]
#v(0.35in)
#letter-grid("letter-")

// ===== The 26 letter pages: landscape, poster left, koan right =====
#set page(flipped: true, margin: 0pt, numbering: none, footer: none)
#for (i, l) in map.letters.enumerate() [
  #page[
    #anchor("letter-" + l.letter)
    #bookmark(2, l.letter + " — " + l.title)
    #grid(
      columns: (50%, 50%),
      rows: 100%,
      // Left half: facer full-bleed. Art is 2:3 (0.667); half-landscape is
      // 5.5x8.5 (0.647): fit "cover" crops the sliver. No letterbox, no distortion.
      box(width: 100%, height: 100%, clip: true,
        image("/" + l.facer, width: 100%, height: 100%, fit: "cover")),
      // Right half: the koan ONLY, centered in generous white space. The poster
      // is the loud layer; this is the quiet layer.
      align(center + horizon,
        pad(x: 0.85in, {
          // Ragged-centered, globally optimized breaks, and the final two words
          // bound with a no-break space (template-side) so no koan ends on a
          // single-word line.
          set par(justify: false, linebreaks: "optimized")
          let parts = l.koan.split(" ")
          let bound = if parts.len() > 1 {
            parts.slice(0, parts.len() - 1).join(" ") + "\u{00a0}" + parts.last()
          } else { l.koan }
          text(size: 17pt, style: "italic", bound)
        })),
    )
    // Small page furniture on the quiet half: page number + home link.
    #place(bottom + right, dx: -0.45in, dy: -0.4in,
      text(size: 8pt, fill: luma(45%))[
        #jump("grid-index")[⌂] #h(0.8em) #context counter(page).display()
      ])
  ]
]

// ===== Back matter: portrait again =====
#set page(flipped: false, margin: (x: 1.1in, y: 1in), numbering: "1",
  number-align: center, footer: auto)
#include "/pdf/_generated/back_all.typ"

// ===== Coloring section: intro page, then one lineart per page, zero chrome =====
#pagebreak()
#anchor("coloring-section")
#heading(level: 1, outlined: true)[Coloring Pages]
#include "/pdf/_generated/coloring_intro.typ"
// The section's own linked grid: same component, targets the coloring pages.
#v(0.25in)
#letter-grid("coloring-", cell: 1in, size: 40pt)

#set page(margin: 0.35in, numbering: none, footer: none)
#for l in map.letters [
  #page[
    #anchor("coloring-" + l.letter)
    #bookmark(2, "Coloring: " + l.letter + " — " + l.title)
    #align(center + horizon, image("/" + l.lineart, height: 100%, fit: "contain"))
  ]
]

// ===== Final page =====
#set page(margin: (x: 1.1in, y: 1in), numbering: none, footer: none)
#page[
  #align(center + horizon)[
    #text(size: 16pt, tracking: 2pt)[THIS PAGE INTENTIONALLY LEFT BLANK]
    #v(2.2em)
    #block(width: 4.4in,
      text(size: 9.5pt, style: "italic", fill: luma(28%))[
        Upon review, the Committee finds the above statement renders this page
        non-blank. A remediation plan is under development. Estimated completion:
        eventually.
      ])
    #v(3em)
    #text(size: 12pt, tracking: 1.5pt)[THE END (pending final approval)]
  ]
]
